name: build arc python
description: build arc python
runs:
  using: "composite"
  steps:
    - name: Configure python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install python dependencies
      shell: bash
      run: |
        cd python
        pip install mlflow>=2.2.2 splink>=3.5.4 hyperopt>=0.2.5
        pip install build wheel pyspark==${{ matrix.spark }}
        pip install .
    - name: Test and build python package
      shell: bash
      run: |
        cd python
        python -m unittest
        python -m build
    - name: Copy python artifacts to GH Actions run
      shell: bash
      run: |
        mkdir -p staging
        cp python/dist/*.whl staging