control_parameters:
  dist_rule_monthly:
    EQUAL: N
    HISTORICAL: N
    PREDEFINED_SPLIT: Y
  dist_rule_weekly:
    AGGRESSIVE: N
    EQUAL: Y
  final_output_level:
    MONTHLY: N
    QUARTERLY: Y
    WEEKLY: N
  monthly_dist_split: null
  weekly_max_tp_aggresive: null
file_paths:
  asset_availability: ./Data_Files/Asset_Availability.csv
  constraint_segment: ./Data_Files/Constraint_segment.csv
  customer_data: ./Data_Files/Sample_HCP_Master_Demo.csv
  engagement_goal: ./Data_Files/Eng_Target_File_Demo.csv
  extra_constraint_file: null
  historical_data: ./Data_Files/HCP_Historical_Data_Demo.csv
  min_gap: ./Data_Files/Min_Gap_Constraints - Copy.csv
  mmix_output: ./Data_Files/Marketing_Mix_Input_Demo.csv
  model: null
  model_cols: null
  model_input_data: null
  priority: ./Data_Files/HCP_Channel_Priority.csv
  vendor_contract: ./Data_Files/Vendor_Contract.csv
output:
  output_folder_path: ./Outputs
  run_id: ''
run_period:
  end_date: '2024-12-31'
  refresh_date: '2024-06-01'
  start_date: '2024-05-02'
table_names:
  asset_availability: asset_availability
  constraint_segment: constraint_segment
  customer_data: customer_data
  engagement_goal: engagement_goal
  extra_constraint_file: null
  historical_data: historical_data
  min_gap: min_gap
  mmix_output: mmix_output
  model: null
  model_cols: null
  model_input_data: null
  priority: priority
  vendor_contract: vendor_contract
