outcome:
  name: sales
  intercept:
    mu: 0
    sd: 10
  sigma:
    beta: 5
  scale: 100000
media:
  adwords:
    beta:
      sd: 1
    saturation:
      alpha: 3
      beta: 1
  facebook:
    beta:
      sd: 1
    saturation:
      alpha: 3
      beta: 1
  linkedin:
    beta:
      sd: 1
    geometric_adstock:
      alpha: 1
      beta: 3
    saturation:
      alpha: 3
      beta: 1
index_vars: []
control_vars: []